server:
  port: 8086
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8090"
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
  application:
    name: mango-menu
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.siques.mangocore.entity
management:
  endpoints:
    web:
      exposure:
        include: "*"