package cn.siques.mangocore.entity;

public class SysConfigWithBLOBs extends SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.remarks
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    private byte[] remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.remarks
     *
     * @return the value of sys_config.remarks
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    public byte[] getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.remarks
     *
     * @param remarks the value for sys_config.remarks
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    public void setRemarks(byte[] remarks) {
        this.remarks = remarks;
    }
}