server:
  port: 8086
spring:
  boot:
    admin:
      client:
        url: "http://106.54.247.224:8090"
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://106.54.247.224:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
  application:
    name: mango-menu
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.247.224:8848
  redis:
    host: 106.54.247.224
    port: 6379
    database: 0
    password: heshenghao
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.siques.mangocore.entity
management:
  endpoints:
    web:
      exposure:
        include: "*"