server:
  port: 8086
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8984/oauth/check_token
      jwt:
        key-alias: siquesWeb
        # 如果没有此项会去请求授权服务器获取
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkF9SyMHeGAsLMwbPsKj/
          xpEtS0iCe8vTSBnIGBDZKmB3ma20Ry0Uzn3m+f40RwCXlxnUcvTw7ipoz0tMQERQ
          b3X4DkYCJXPK6pAD+R9/J5odEwrO2eysByWfcbMjsZw2u5pH5hleMS0YqkrGQOxJ
          pzlEcKxMePU5KYTbKUJkhOYPY+gQr61g6lF97WggSPtuQn1srT+Ptvfw6yRC4bdI
          0zV5emfXjmoLUwaQTRoGYhOFrm97vpoKiltSNIDFW01J1Lr+l77ddDFC6cdiAC0H
          5/eENWBBBTFWya8RlBTzHuikfFS1gP49PZ6MYJIVRs8p9YnnKTy7TVcGKY3XZMCA
          mwIDAQAB
          -----END PUBLIC KEY-----
        key-uri: http://localhost:8984/oauth/token_key
      id: test
    client:
      client-id: siquesAdmin
      client-secret: 123456
      access-token-uri: http://localhost:8984/oauth/token
      scope: READ

spring:
  boot:
    admin:
      client:
        url: "http://106.54.247.224:8090"
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://106.54.247.224:3306/mango?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
  application:
    name: mango-menu
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.247.224:8848
  redis:
    host: 106.54.247.224
    port: 6379
    database: 0
    password: heshenghao
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.siques.mangocore.entity
management:
  endpoints:
    web:
      exposure:
        include: "*"