package cn.siques.mango.entity;

public class SysDictKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbggenerated Mon Jun 29 20:40:38 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }
}