package cn.siques.mango.entity;

import java.io.Serializable;

/**
 * Model class of 系统操作日志.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysLog implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private Long id;

	/** 用户名. */
	private String userName;

	/** 用户操作. */
	private String operation;

	/** 请求方法. */
	private String method;

	/** 请求参数. */
	private String params;

	/** 执行时间. */
	private Long time;

	/** IP地址. */
	private String ip;

	/**
	 * Constructor.
	 */
	public SysLog() {
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param userName
	 *            用户名
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the 用户操作.
	 * 
	 * @param operation
	 *            用户操作
	 */
	public void setOperation(String operation) {
		this.operation = operation;
	}

	/**
	 * Get the 用户操作.
	 * 
	 * @return 用户操作
	 */
	public String getOperation() {
		return this.operation;
	}

	/**
	 * Set the 请求方法.
	 * 
	 * @param method
	 *            请求方法
	 */
	public void setMethod(String method) {
		this.method = method;
	}

	/**
	 * Get the 请求方法.
	 * 
	 * @return 请求方法
	 */
	public String getMethod() {
		return this.method;
	}

	/**
	 * Set the 请求参数.
	 * 
	 * @param params
	 *            请求参数
	 */
	public void setParams(String params) {
		this.params = params;
	}

	/**
	 * Get the 请求参数.
	 * 
	 * @return 请求参数
	 */
	public String getParams() {
		return this.params;
	}

	/**
	 * Set the 执行时间.
	 * 
	 * @param time
	 *            执行时间
	 */
	public void setTime(Long time) {
		this.time = time;
	}

	/**
	 * Get the 执行时间.
	 * 
	 * @return 执行时间
	 */
	public Long getTime() {
		return this.time;
	}

	/**
	 * Set the IP地址.
	 * 
	 * @param ip
	 *            IP地址
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * Get the IP地址.
	 * 
	 * @return IP地址
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SysLog other = (SysLog) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
