package cn.siques.mango.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 菜单管理.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysMenu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private Long id;

	/** 菜单名称. */
	private String name;

	/** 父菜单 ID 一级菜单为 0. */
	private Long parentId;

	/** 菜单URL,类型：1.普通页面（如用户管理 /sys/user）2.嵌套完整页面3.嵌套服务器页面 如 iframe:/druid/login.html,iframe前缀会替换为服务器地址. */
	private String url;

	/** 权限(多个用逗号分开，如：sys:user:add,sys:user:edit). */
	private String perms;

	/** 类型 0：目录 1：菜单 2：按钮. */
	private Integer type;

	/** 菜单图标. */
	private String icon;

	/** 排序. */
	private Integer orderNum;

	/** 创建人. */
	private String createBy;

	/** 创建时间. */
	private Date createTime;

	/** 更新人. */
	private String lastUpdateBy;

	/** 更新时间. */
	private Date lastUpdateTime;

	/** 是否删除 -1：已删除 0：正常. */
	private Byte delFlag;

	/** The set of 角色菜单管理. */
	private Set<SysRoleMenu> sysRoleMenuSet;

	/**
	 * Constructor.
	 */
	public SysMenu() {
		this.sysRoleMenuSet = new HashSet<SysRoleMenu>();
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 菜单名称.
	 * 
	 * @param name
	 *            菜单名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 菜单名称.
	 * 
	 * @return 菜单名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 父菜单 ID 一级菜单为 0.
	 * 
	 * @param parentId
	 *            父菜单 ID 一级菜单为 0
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the 父菜单 ID 一级菜单为 0.
	 * 
	 * @return 父菜单 ID 一级菜单为 0
	 */
	public Long getParentId() {
		return this.parentId;
	}

	/**
	 * Set the 菜单URL,类型：1.普通页面（如用户管理 /sys/user）2.嵌套完整页面3.嵌套服务器页面 如 iframe:/druid/login.html,iframe前缀会替换为服务器地址.
	 * 
	 * @param url
	 *            菜单URL,类型：1.普通页面（如用户管理 /sys/user）2.嵌套完整页面3.嵌套服务器页面 如 iframe:/druid/login.html,iframe前缀会替换为服务器地址
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Get the 菜单URL,类型：1.普通页面（如用户管理 /sys/user）2.嵌套完整页面3.嵌套服务器页面 如 iframe:/druid/login.html,iframe前缀会替换为服务器地址.
	 * 
	 * @return 菜单URL,类型：1.普通页面（如用户管理 /sys/user）2.嵌套完整页面3.嵌套服务器页面 如 iframe:/druid/login.html,iframe前缀会替换为服务器地址
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * Set the 权限(多个用逗号分开，如：sys:user:add,sys:user:edit).
	 * 
	 * @param perms
	 *            权限(多个用逗号分开，如：sys:user:add,sys:user:edit)
	 */
	public void setPerms(String perms) {
		this.perms = perms;
	}

	/**
	 * Get the 权限(多个用逗号分开，如：sys:user:add,sys:user:edit).
	 * 
	 * @return 权限(多个用逗号分开，如：sys:user:add,sys:user:edit)
	 */
	public String getPerms() {
		return this.perms;
	}

	/**
	 * Set the 类型 0：目录 1：菜单 2：按钮.
	 * 
	 * @param type
	 *            类型 0：目录 1：菜单 2：按钮
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * Get the 类型 0：目录 1：菜单 2：按钮.
	 * 
	 * @return 类型 0：目录 1：菜单 2：按钮
	 */
	public Integer getType() {
		return this.type;
	}

	/**
	 * Set the 菜单图标.
	 * 
	 * @param icon
	 *            菜单图标
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * Get the 菜单图标.
	 * 
	 * @return 菜单图标
	 */
	public String getIcon() {
		return this.icon;
	}

	/**
	 * Set the 排序.
	 * 
	 * @param orderNum
	 *            排序
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * Get the 排序.
	 * 
	 * @return 排序
	 */
	public Integer getOrderNum() {
		return this.orderNum;
	}

	/**
	 * Set the 创建人.
	 * 
	 * @param createBy
	 *            创建人
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建人.
	 * 
	 * @return 创建人
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新人.
	 * 
	 * @param lastUpdateBy
	 *            更新人
	 */
	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	/**
	 * Get the 更新人.
	 * 
	 * @return 更新人
	 */
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param lastUpdateTime
	 *            更新时间
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	/**
	 * Set the 是否删除 -1：已删除 0：正常.
	 * 
	 * @param delFlag
	 *            是否删除 -1：已删除 0：正常
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 是否删除 -1：已删除 0：正常.
	 * 
	 * @return 是否删除 -1：已删除 0：正常
	 */
	public Byte getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the set of the 角色菜单管理.
	 * 
	 * @param sysRoleMenuSet
	 *            The set of 角色菜单管理
	 */
	public void setSysRoleMenuSet(Set<SysRoleMenu> sysRoleMenuSet) {
		this.sysRoleMenuSet = sysRoleMenuSet;
	}

	/**
	 * Add the 角色菜单管理.
	 * 
	 * @param sysRoleMenu
	 *            角色菜单管理
	 */
	public void addSysRoleMenu(SysRoleMenu sysRoleMenu) {
		this.sysRoleMenuSet.add(sysRoleMenu);
	}

	/**
	 * Get the set of the 角色菜单管理.
	 * 
	 * @return The set of 角色菜单管理
	 */
	public Set<SysRoleMenu> getSysRoleMenuSet() {
		return this.sysRoleMenuSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SysMenu other = (SysMenu) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
