package cn.siques.mango.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of 用户管理.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SysUser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 编号. */
	private Long id;

	/** 角色名称. */
	private String name;

	/** 昵称. */
	private String nickName;

	/** 头像. */
	private String avatar;

	/** 密码. */
	private String password;

	/** 加密盐. */
	private String salt;

	/** 邮箱. */
	private String email;

	/** 手机号. */
	private String mobile;

	/** 状态 0：禁用 1：正常. */
	private Byte status;

	/** 机构 ID. */
	private Long deptId;

	/** 创建人. */
	private String createBy;

	/** 创建时间. */
	private Date createTime;

	/** 更新人. */
	private String lastUpdateBy;

	/** 更新时间. */
	private Date lastUpdateTime;

	/** 是否删除 -1：已删除 0：正常. */
	private Byte delFlag;

	/** The set of 用户角色表. */
	private Set<SysUserRole> sysUserRoleSet;

	/**
	 * Constructor.
	 */
	public SysUser() {
		this.sysUserRoleSet = new HashSet<SysUserRole>();
	}

	/**
	 * Set the 编号.
	 * 
	 * @param id
	 *            编号
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the 编号.
	 * 
	 * @return 编号
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 角色名称.
	 * 
	 * @param name
	 *            角色名称
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the 角色名称.
	 * 
	 * @return 角色名称
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the 昵称.
	 * 
	 * @param nickName
	 *            昵称
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * Get the 昵称.
	 * 
	 * @return 昵称
	 */
	public String getNickName() {
		return this.nickName;
	}

	/**
	 * Set the 头像.
	 * 
	 * @param avatar
	 *            头像
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * Get the 头像.
	 * 
	 * @return 头像
	 */
	public String getAvatar() {
		return this.avatar;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 加密盐.
	 * 
	 * @param salt
	 *            加密盐
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * Get the 加密盐.
	 * 
	 * @return 加密盐
	 */
	public String getSalt() {
		return this.salt;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 手机号.
	 * 
	 * @param mobile
	 *            手机号
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * Get the 手机号.
	 * 
	 * @return 手机号
	 */
	public String getMobile() {
		return this.mobile;
	}

	/**
	 * Set the 状态 0：禁用 1：正常.
	 * 
	 * @param status
	 *            状态 0：禁用 1：正常
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * Get the 状态 0：禁用 1：正常.
	 * 
	 * @return 状态 0：禁用 1：正常
	 */
	public Byte getStatus() {
		return this.status;
	}

	/**
	 * Set the 机构 ID.
	 * 
	 * @param deptId
	 *            机构 ID
	 */
	public void setDeptId(Long deptId) {
		this.deptId = deptId;
	}

	/**
	 * Get the 机构 ID.
	 * 
	 * @return 机构 ID
	 */
	public Long getDeptId() {
		return this.deptId;
	}

	/**
	 * Set the 创建人.
	 * 
	 * @param createBy
	 *            创建人
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * Get the 创建人.
	 * 
	 * @return 创建人
	 */
	public String getCreateBy() {
		return this.createBy;
	}

	/**
	 * Set the 创建时间.
	 * 
	 * @param createTime
	 *            创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建时间.
	 * 
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新人.
	 * 
	 * @param lastUpdateBy
	 *            更新人
	 */
	public void setLastUpdateBy(String lastUpdateBy) {
		this.lastUpdateBy = lastUpdateBy;
	}

	/**
	 * Get the 更新人.
	 * 
	 * @return 更新人
	 */
	public String getLastUpdateBy() {
		return this.lastUpdateBy;
	}

	/**
	 * Set the 更新时间.
	 * 
	 * @param lastUpdateTime
	 *            更新时间
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * Get the 更新时间.
	 * 
	 * @return 更新时间
	 */
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	/**
	 * Set the 是否删除 -1：已删除 0：正常.
	 * 
	 * @param delFlag
	 *            是否删除 -1：已删除 0：正常
	 */
	public void setDelFlag(Byte delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * Get the 是否删除 -1：已删除 0：正常.
	 * 
	 * @return 是否删除 -1：已删除 0：正常
	 */
	public Byte getDelFlag() {
		return this.delFlag;
	}

	/**
	 * Set the set of the 用户角色表.
	 * 
	 * @param sysUserRoleSet
	 *            The set of 用户角色表
	 */
	public void setSysUserRoleSet(Set<SysUserRole> sysUserRoleSet) {
		this.sysUserRoleSet = sysUserRoleSet;
	}

	/**
	 * Add the 用户角色表.
	 * 
	 * @param sysUserRole
	 *            用户角色表
	 */
	public void addSysUserRole(SysUserRole sysUserRole) {
		this.sysUserRoleSet.add(sysUserRole);
	}

	/**
	 * Get the set of the 用户角色表.
	 * 
	 * @return The set of 用户角色表
	 */
	public Set<SysUserRole> getSysUserRoleSet() {
		return this.sysUserRoleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SysUser other = (SysUser) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
