
spring:
  rabbitmq:
    host: 106.54.247.224
    username: admin
    password: heshenghao
    port: 5672
    virtual-host: my_vhost
    listener:
      simple:
        acknowledge-mode: auto
  mail:
    host: smtp.qq.com
    port: 465
    username: 943452349@qq.com
    # 使用 jasypt 加密密码，使用com.xkcoding.email.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password: yxlutcwvevjobebe
#    password: lilqtrclktocbbia
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: 943452349@qq.com
# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: spring-boot-demo
server:
  port: 8098