spring:
  application:
    name: mango-socketio
  redis:
    database: 0
    port: 6379
    password: heshenghao
    host: 106.54.247.224
server:
  port: 8085
ws:
  server:
    port: 8091
    host: localhost
