server:
  port: 8090
spring:
  application:
      name: mango-monitor
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.247.224:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
