server:
  port: 9001
spring:
  application:
    name: mango-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin_route   #路由id 没有固定规则但要求唯一，配合服务名
          #          uri: http://localhost:8001 # 匹配提供服务的路由地址
          uri: lb://mango-admin
          predicates:
            - Path=/consumer/api/sys/v1/pub/**    #断言，路径相匹配进行路由
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848