FROM node:10.16.3
WORKDIR /usr/src/nuxt
ENV HOST 0.0.0.0
COPY . . 
COPY .env .env
COPY .npmrc .npmrc
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install
RUN npm run build 

EXPOSE 3002
CMD ["npm","start"]